# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a6357b57a3a49dcf38334ede563a452578e48fd0b8483423474dc0e354cc6b3703e091aa198f8f0930960d6b017222b82929a510d50690e1fa1ae4ce7360ac5

test:
  secret_key_base: ad918de86e3a65a0d2bdda7b30a7b75caee6d72dae50823846743d0c47af8c7319c85d25a050fdf7bea2afd675caf242cf99d89d2860f1d607d03b1c8aa8b3f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
